name: PartyCmdSenderExample
main: net.simplyrin.bungeefriends.api.spigot.example.PartyCmdSenderExample
version: 1.0.0
api-version: 1.13
author: BungeeFriends
description: 展示如何使用PartyCmdSender功能的示例插件
depend: [BungeeFriendsAPI-Spigot]

commands:
  partycmd:
    description: 让队长执行命令，队员跟随执行
    usage: /partycmd <命令> [参数...]
    permission: partycmdexample.use

permissions:
  partycmdexample.use:
    description: 允许使用/partycmd命令
    default: true