# BungeeFriendsAPI-Spigot 配置文件

# PartyCmdSender 配置
partycmdsender:
  # 需要监听的命令列表
  # 支持以下格式：
  # - "完整命令" - 精确匹配整个命令
  # - "命令前缀 $args" - 匹配命令前缀，后面的参数会被传递
  # - "命令" - 匹配命令名称，忽略参数
  commands:
    - "example"
    - "example &args"
    - "bw join &args"
  
  # 调试模式
  debug: false
  
  # 命令执行延迟（单位：tick，20tick = 1秒）
  command-delay: 10